apiVersion: v1
kind: Service
metadata:
  name: masonic-web-services
  namespace: default
spec:
  selector:
    app: masonic-web-services
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
